cps/templates/detail.html

Mini Pull request.
should i make such small pull request or wait for more changes to pull this?

show 'read in browser' only for epubs

---

cps/static/css/style.css
cps/templates/layout.html
cps/templates/search_form.html
cps/web.py

Adds an advanced search button in the top.
you can search by multiple tag selection and by title and author.

add advanced search

---

cps/book_formats.py
cps/epub.py
cps/fb2.py
cps/uploader.py
cps/web.py

Hi,
I need to be able to upload not only pdfs, but epub and fb2 as well. To make implementing this a bit easier, I've slightly refactored the web.py code, so someone else may add even more formats some time.
Thanks,
Pavel

Upload more than pdf

---

cps/ub.py

> AttributeError: 'NoneType' object has no attribute 'nickname'
ERROR:cps.web:Exception on /config [GET]

Fix typo; raise exception when creating database

---

cps/web.py

, instead of + because get_main_dir is not endswith os.sep

Fix vendorpath

---

.gitignore

add vendor/kindlegen to be .gitignore

.gitignore kindlegen in vendor folder

---

cps/book_formats.py
cps/db.py
cps/epub.py
cps/fb2.py
cps/uploader.py
cps/web.py

Now upload will add languages according to opf file
<dc:language>tag

Bookmeta patch 20170302

---

cps/book_formats.py
cps/epub.py
cps/uploader.py
cps/web.py

Just refactor epub upload logic
Reuse BookMeta.description field instead of BookMeta.comments
Cover detection is no longer hard code as <pkg:item name="cover">

[Refactor] patch bookmeta 20170304

---

readme.md

I added a nohup command in the first subparagraph "Quick start".

I modified "Quick start" in readme.md

---

cps/web.py

Fix issue #148

---

cps/web.py

request.headers is not type of dict.
It is belonged to wsgi....headers type.
Fix #163  #121

Fix Download Bug.

---

cps/db.py
cps/templates/book_edit.html
cps/web.py

I needed an int for Page Numbers

support int in custom fields

---

cps/static/css/style.css
cps/templates/detail.html

* Use block label to toggle the checkbox
* Submit form when checkbox's value changes (regardless of whether mouse is used or not)
* Remove unused code

Simplify the read functionality's code

---

cps/web.py

Displays the read/unread counts in the title and heading of the Read & Unread pages.

Show read/unread counts

---

cps/static/js/get_meta.js

Use TinyMCE's API to update the description's content

---

cps/templates/detail.html
cps/templates/discover.html
cps/templates/index.html
cps/templates/layout.html
cps/templates/search.html
cps/templates/search_form.html

I ran some of the pages through Chrome 60's Lighthouse audit and it came back with some low-hanging issues. I've resolved many of them, split up by category across commits (in case some are desirable and others are not).

Lighthouse audit items

---

cps/epub.py
cps/web.py

Added new metadata getter for epub files that include series and series_index information when they are uploaded.
Implements [#251](https://github.com/janeczku/calibre-web/issues/251) from epub metadata

Added series and series index metadata handler for epubs

---

cps/ub.py

Add mature_content property to Anonymous class

---

cps/web.py

Instead of duplicating functionality across lots of functions, combine it into one common function. It makes reading and modifying it much easier.

(cleanup) Move common filters into function

---

cps/web.py

Seems to make a difference sometimes.
Ref #300

SQLAlchemy bool

---

cps/templates/search.html

fix typo: diffrent -> different

---

cps/translations/nl/LC_MESSAGES/messages.po

I've added some missing translations and edit some faulty ones. Not finished yet, will continue later on! ;-)

Updated Dutch translations

---

cps/web.py

Ensure variables exist before they're used

---

cps/static/js/main.js
cps/templates/layout.html

Add a progress bar to the upload form. The bar takes the place of the upload button when the form is submitted.

Add progress bar to upload form

---

cps/static/js/reading/epub.js
cps/templates/read.html
cps/ub.py
cps/web.py

Save ePub bookmark to database. Also use library's built-in restore feature to restore all information from localStorage.
I haven't investigated how to hook into the PDF library yet, but its bookmarks are similar to ePub's in that they're just a specially formatted string. We won't have to change the database record to accommodate them.
Ref #266 and #285

Save ePub bookmarks to database

---

cps/static/js/get_meta.js

Translate 10-based rating to 5-based

---

cps/static/js/reading/epub.js
cps/templates/read.html
cps/web.py

Disable bookmarking when anonymous users are reading

---

cps/templates/detail.html
cps/templates/index.xml
cps/templates/layout.html
cps/templates/read.html
cps/templates/shelf.html
cps/ub.py
cps/web.py

is_active, is_authenticated, and is_anonymous should be properties in both the UserBase and Anonymous classes to be consistent with flask_login.  Not making them properties breaks the login_required decorator in flask_login.  Additionally they're only ever called on instances of the classes so should not be classmethods in UserBase.
Previous implementation of login_required_if_no_ano decorator required the server to be restarted in order for the anonymous browsing option to take effect.
Should resolve issues #365 and #366.

Anonymous Browser Fix

---

cps/translations/nl/LC_MESSAGES/messages.po

Added missing translations and fixed some strings. Not sure if I need to generate a new `.mo` file.

Updated Dutch translation

---

cps/web.py

Python3 seems to have removed the bytes.decode function.
It should still work with python2 (simple if).

added python3 compatibility for comic reader

---

cps/static/css/kthoom.css
cps/static/js/kthoom.js
cps/templates/readcbr.html
cps/web.py

-A slimmer and more subtle progress bar to the top which only shows the page number on hover 
-Thumbnail list now scrolls to the current page on open or page change
-Added @andy29485's request for controlling page with space/shift+space
-Added the book title to the top of the page 
-Fixed IE11 failing on imagecallback

New progress bar & IE11 fix

---

cps/templates/detail.html
cps/web.py

Just a minor inconvenience to press that second button when there's only one option anyway.
Also a bit of code cleanup.

Auto select format for reading if only one

---

cps/db.py
cps/templates/feed.xml

replace space separating date from time with 'T'

fix #513 OPDS updated date format invalid per Atom specification

---

readme.md

Wondered if you'd mind adding a bit about our containers to the readme, might be nice for people using other architectures.

Other docker containers

---

readme.md

https://github.com/janeczku/calibre-web/issues/523

Readme update for nginx proxy

---

cps/templates/search.html

Show add to shelf button only when there is a result

---

cps/worker.py

Check to see if target book format already exists before executing conversion.

Fix to #625 

---

cps/web.py

There was an incorrect parameter.

Delete book function fixed

---

cps/translations/es/LC_MESSAGES/messages.po

update Spanish translation

---

readme.md

Added note to README to account for a pip install error in Ubuntu - which I'm assuming should be one of the most used distros to run the server.

Modify Readme for Ubuntu install bug

---

cps/templates/author.html
cps/templates/discover.html
cps/templates/index.html
cps/templates/search.html
cps/templates/shelf.html

Add anchor tags (links) to book titles

Add anchor tags to titles #665

---

cps/static/js/caliBlur.js

This should remedy the way publishers are not formatting correctly on book details page

Fix publisher not formatting correct (caliBlur)

---

cps/templates/layout.html

proposed class changes will assist caliBlur in targeting elements, resolving language compatibility issues.

Add classes to shelves for easier css selection

---

cps/templates/index.html

Assist caliBlur in targeting this element

Add .random-books class to random books div

---

cps/web.py

i fixed an issue that i created #853

fixed a bug that affects allowing password change for users

---

cps/helper.py
requirements.txt

Not support svg right now. https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html

Support issue: #843

---

.gitignore
cps/__init__.py
cps/about.py
cps/admin.py
cps/cli.py
cps/config_sql.py
cps/constants.py
cps/converter.py
cps/db.py
cps/editbooks.py
cps/helper.py
cps/logger.py
cps/server.py
cps/services/simpleldap.py
cps/ub.py
cps/web.py
cps/worker.py

Entirely optional. Comments welcome.
BTW. In cps.py, isn't `sys.path[0]` always be the same as `os.path.dirname(os.path.abspath(__file__))` ? In all my tests, it has been. Is there a situation when it is not?

Minor code clean-ups

---

optional-requirements.txt

https://github.com/googleapis/google-api-python-client/issues/453
Closes https://github.com/janeczku/calibre-web/issues/1010
I can confirm that it solved it in my case

requirements: Update google-api-python-client and httplib2 versions

---

cps/web.py

Added public /reconnect endpoint

---

cps/templates/book_edit.html

Allow for finer steps in serie-index

fix issue #1064

---

cps/static/css/style.css
cps/templates/shelf_order.html

Current shelf order view is just a list of book titles.
I have added some info like the book cover, book series and book authors.
This way books can be easily identified and sorted.

It adds info to shelf order view

---

cps/admin.py
cps/templates/user_edit.html
cps/ub.py
cps/web.py

Add the possibility to change the username (#936)

---

cps/editbooks.py
cps/helper.py
cps/templates/book_exists_flash.html
cps/templates/layout.html

Check for duplicate imported ebook and show warning

Checking and warrying on possible duplicity in upload

---

cps/editbooks.py

Merge metadata of uploaded book versions.

---

cps/db.py
cps/web.py

/reconnect was broken by https://github.com/janeczku/calibre-web/commit/006e596c7221729c9a37b79037fa72bb88506492 .

Fix /reconnect endpoint

---

cps/db.py
cps/editbooks.py
cps/templates/book_edit.html

- remove float datatype from cc_exceptions
- handle float datatype like int or bool
- change edit template to modify input step (0.01 precision, like
in calibre UI)

custom columns: add Float type support

---

cps/translations/sv/LC_MESSAGES/messages.po

Update Swedish translation

---

cps/translations/it/LC_MESSAGES/messages.po

Update italian message.po

---

cps/translations/it/LC_MESSAGES/messages.po

message.po italian

---

cps/kobo.py

* Add a timeout to prevent hanging when the KoboStore isn't reachable.
* Add back a the dummy auth implementation for when proxying is
disabled.
* Return the dummy auth response as a fallback when failing to contact
the KoboStore.
* Don't contact the KoboStore during the /sync API call when proxying is
disabled.

Make KoboStore proxying more robust.

---

cps/translations/it/LC_MESSAGES/messages.po

Hello, 
updated one more time the translation :-)
I think the string "Author list" is missing.
Thank you!
Quimm

udate message.po in italian

---

cps/static/js/get_meta.js

Fix bug in authors list when getting metadata

---

.gitignore
cps/templates/user_edit.html
cps/translations/de/LC_MESSAGES/messages.po
cps/translations/es/LC_MESSAGES/messages.po
cps/translations/fr/LC_MESSAGES/messages.po
cps/translations/hu/LC_MESSAGES/messages.po
cps/translations/it/LC_MESSAGES/messages.po
cps/translations/ja/LC_MESSAGES/messages.po
cps/translations/km/LC_MESSAGES/messages.po
cps/translations/nl/LC_MESSAGES/messages.po
cps/translations/pl/LC_MESSAGES/messages.po
cps/translations/ru/LC_MESSAGES/messages.po
cps/translations/sv/LC_MESSAGES/messages.po
cps/translations/uk/LC_MESSAGES/messages.po
cps/translations/zh_Hans_CN/LC_MESSAGES/messages.po
cps/ub.py
cps/web.py

Provides the ability to restrict the user's view to books having a configurable set of tags

Restrict a user to a set of tags

---

cps/translations/zh_Hans_CN/LC_MESSAGES/messages.po

btw, [crowdin.com](https://crowdin.com/) is a good tool to host i18n work.

Update Chinese translation

---

cps/kobo.py

This fixes the "Sort: Date added" option on the device.

[Kobo] Fix issue where books aren't correctly ordered by Date Added

---

cps/static/js/get_meta.js
cps/templates/book_edit.html

This will add the possibility to fetch metadata for comicbook

[enhancement] Add ComicVine API

---

cps/translations/it/LC_MESSAGES/messages.po

italian updated version of messages.po

---

cps/kobo.py
cps/services/SyncToken.py

Quickly tested:
- Marking book as read on the device correctly updated CalibreWeb
- Deleting book on the device correctly moved it to the CalibreWeb archive.

Fix #1164 merge.

---

cps/static/js/caliBlur.js

Updated to exclude new modules

---

cps/translations/it/LC_MESSAGES/messages.po

Update italian version of message.po

---

cps/translations/it/LC_MESSAGES/messages.po

Updated italian version of messages.po

---

cps/templates/layout.html

Keep previous search and focus.
So we can add more words to search bar faster

Keep previous search value and focus

---

cps/helper.py
cps/web.py

It is far easier to search for a
series or anything and see
books in sort order

Sort search result by Books sort

---

cps/comic.py
cps/constants.py
cps/helper.py

This should prevent a couple of crashes due to undeclared variables.

Move a few variables around

---

cps/translations/it/LC_MESSAGES/messages.po

Updated version of italian.po

---

cps/kobo.py

Fix issue with cover images introduced during the merge of #1277.

[Kobo] Fix covers in proxy mode.

---

cps/translations/it/LC_MESSAGES/messages.po

just a little update for coherence with Read/da leggere -> Archived/da archiviare.
Sorry :-)

updated messages.po

---

cps/static/js/caliBlur.js

- Add alt attributes to images
- Fix a broken tag

Minor fixes to caliBlur.js

---

cps/__init__.py

- Samesite for session cookies as well as the remember me ones
- Httponly

Improve a bit the cookie's hardening

---

cps/__init__.py

See https://flask-login.readthedocs.io/en/latest/#session-protection for
details

Use strong sessions protection

---

cps/static/css/style.css

Correcting 'box-sizeing' to 'box-sizing' in two places

Fix: correct property typo

---

cps/templates/layout.html

Base on feedback of users, I disable the auto focus if a search is not in progress.

activate search focus if search in progress

---

cps/helper.py
cps/web.py

Allow advance search
Remove duplicate status on show

Handle read config

---

cps/translations/it/LC_MESSAGES/messages.po

Updated version of italian message.po

---

cps/translations/it/LC_MESSAGES/messages.po

updated italian version of message.po

---

cps/translations/cs/LC_MESSAGES/messages.po

I could not find any guide on contributing translations but here are some strings. Not sure if someone needs to be compiled or not.

Some czech translations

---

cps/static/css/caliBlur.min.css
cps/templates/layout.html

Another styling fix
Before:
After:

Pagination fix for caliBlur!

---

cps/oauth_bb.py

Google oauth provider obtain link was pointing to github

Fix typo in oauth_bb.py

---

cps/translations/it/LC_MESSAGES/messages.po

italian version of messages.po updated

---

cps/static/css/caliBlur.min.css

1622_updated_css

---

cps/translations/es/LC_MESSAGES/messages.po

Hi,
I've added some missings translations in Spanish ;)

Add some missings translations

---

cps/helper.py

Fixes #1589
Super simple PR, was in that section with my other PR and thought I'd take care of it 😁

Add link to book for convert task

---

cps/translations/it/LC_MESSAGES/messages.po

updated italian message.po

---

cps/translations/zh_Hans_CN/LC_MESSAGES/messages.po

SImple Chinese translation updated.

---

cps/gdrive.py

- removes two levels of indentation
- makes it clear that if the wrong tokens are provided nothing will happen
- remove a useless nested function

Negate a condition

---

cps/static/css/caliBlur.css
cps/static/js/main.js
cps/templates/layout.html

Issue/caliblur 981 - Infinite Scroll on caliBlur Theme

---

cps/kobo.py

Only offer kepub download URL over Kobo sync API when available

Prefer kepub (#1439)

---

cps/translations/nl/LC_MESSAGES/messages.po

NL translation update

---

cps/helper.py
cps/static/css/style.css
cps/templates/author.html
cps/templates/discover.html
cps/templates/grid.html
cps/templates/index.html
cps/templates/search.html
cps/templates/shelf.html
cps/web.py

This is the render.
I need to handle the read status for books.

Bubble read status

---

.github/ISSUE_TEMPLATE/bug_report.md

Nothing important, but it's LinuxServer not Linuxuser.

Correct name for LinuxServer

---

cps/static/js/kthoom.js
cps/web.py

Support webp in comic viewer

---

cps/db.py

changed __repr__ else statement to resolve custom url entries
This allows adding multiple of any kind of url links that you want.

modified to support custom url identifiers

---

cps/translations/es/LC_MESSAGES/messages.po

Updated spanish messages.po

---

cps/admin.py
cps/static/css/caliBlur.css
cps/static/css/listen.css
cps/static/css/main.css
cps/static/css/style.css
cps/static/js/edit_books.js
cps/static/js/filter_grid.js
cps/static/js/main.js

Fix for #1890

---

cps/templates/admin.html
cps/templates/logviewer.html
cps/templates/user_edit.html

When I tried to click a couple of the admin buttons they didn't do anything until I realized there was an anchor inside that was just the text.
This converts the whole anchor to a button like its done elsewhere, which makes the entire button clickable.

Use btn classes on anchors not div so the entire button is clickable

---

README.md

- Shields for PyPi too (downloads and version)
- Switch all logos to white
- Change style to flat-square
- ???

Shield cleanup

---

cps/translations/nl/LC_MESSAGES/messages.po

For any Dutch speaker out there, feel free to correct my translations.

Completed Translation for Dutch (NL)

---

cps/translations/es/LC_MESSAGES/messages.po

updated `cps\translations\es\LC_MESSAGES\messages.po` file for issue: #606

Updated spanish translation

---

cps/translations/fr/LC_MESSAGES/messages.po

The French translation is normally completely now.
I hope it’s all fine.
Thank you for this awesome app !!

Update French translations

---

cps/translations/de/LC_MESSAGES/messages.po

Fix typo in german translation

---

cps/static/js/reading/epub.js
cps/templates/read.html

You could not bookmark without the CSRF token, so I have added it to the HTTP request.

Bookmarking was missing the CSRF

---

cps/translations/fr/LC_MESSAGES/messages.po

I hope everything’s fine !
Thanks for all.

Update French Translation

---

README.md

Hi,
I thought easiest installation option might be interesting on README page. Feel free to add other providers.
Thank you,

Installation on a Cloud Provider wiki link

---

cps/metadata_provider/amazon.py
cps/metadata_provider/comicvine.py
cps/metadata_provider/douban.py
cps/metadata_provider/google.py
cps/metadata_provider/lubimyczytac.py
cps/metadata_provider/scholar.py
cps/search_metadata.py
cps/static/js/edit_books.js
cps/static/js/get_meta.js

Add douban metadate provider
Add exception handling and logger in metadata provider
Add no result message

Add douban metadate provider

---

cps/comic.py
cps/constants.py
cps/editbooks.py
cps/epub.py
cps/fb2.py
cps/uploader.py

This PR extracts pubdate, publisher and non-calibre identifiers from epubs on upload. Solves #2163 
Also removed duplicate parse_xmp in uploader.py

Add pubdate, publisher and identifiers metadata #2163

---

cps/static/css/epub_themes.css
cps/static/css/main.css
cps/static/js/reading/epub.js
cps/templates/read.html

I added a sepia and dark theme to the epub reader. You can select the theme in the settings tab.
Fixes #1960

Feature: Added basic theming to the epub reader

---

cps/translations/uk/LC_MESSAGES/messages.po

Update Ukrainian translation

---

cps/translations/it/LC_MESSAGES/messages.po

Hello, I ran the October 2 update, and this error appeared: 
Merge remote-tracking branch 'it/patch-28'
Calibre-Web does not start again and the container logfile does not allow me to have more information. I proceeded to verify the translation file (I did not find anything strange) and I made some updates of the text.

update message.po (italian)

---

cps/templates/listenmp3.html

Basically, I re-used html code from 'detail.html', removed some elements and added it to the 'listenmp3.html'.

Editing listenmp3.html page to show audiobook info

---

cps/metadata_provider/douban.py

Change search API
Change to return an empty list when an error occurs 
Change the way to get tags
Fix series and publisher perse error
Rename a variable with the same name as the built-in

Update douban metadata provider

---

cps/static/css/caliBlur.css
cps/static/css/caliBlur_override.css

Fixes #2515 
And also fixes a bug which made the datepicker to open far from the input.

Fixes #2515

---

cps/metadata_provider/google.py

Google Covers: strip curl in thumbnail and request higher resolution image

---

cps/translations/id/LC_MESSAGES/messages.po

Fixed typos and inconsistencies.
Defined "Berkas" instead of "File" for English term "File".
Defined "Pengaturan" and its root word "Atur" instead of "Konfigurasi" for English term "Configuration".
Reverting technical terms "Logfile", "access logfile", "Keyfile" to its English origin.

First fix after proofread (Indonesian translation)

---

cps/uploader.py

PdfFileReader -> PdfReader

---

cps/translations/it/LC_MESSAGES/messages.po

* Fix typo
* Improve the already existing translation
* Add new string

Update italian translation

---

cps/web.py

CSP requires some cosmetic corrections

CSP invalid syntax

---

cps/epub.py

- Reduce the amount of nested indentation
- Use proper functions instead of fragile manual parsing

Minor code refactorisation of epub.py

---

cps/templates/readpdf.html
cps/web.py

Enabled byte-range reads when loading PDF file

---

README.md

- Improve formatting and readability with clearer headings and bullet points
- Reorder sections for a more logical flow
- Update installation and quick start steps for better understanding

Update README.md for clarity, formatting, and improved readability

---

README.md

i fubarred the optional calibre layer link somehow, my apologies
thanks for all you guys do, myself and my entire family love calibre-web :)

update readme due to my mistake on link

---

cps/translations/pt_PT/LC_MESSAGES/messages.po

Translation to European portuguese - pt-PT portuguese (Portugal) 
Note 1: 
file messages.mo not created as file was translated directly in browser
Note2: there is already a pt-BR translation but my translation is for the mais portuguese language (code "pt" ou pt-PT)

Create pt-PT translation

---

cps/translations/pt_BR/LC_MESSAGES/messages.po

pt-BR Update messages.po

---

cps/metadata_provider/lubimyczytac.py

Seems like lubimyczytac.pl changed paths in breadcrumbs. Simple xpath update fix #2822 problem. 
Old path (from https://web.archive.org/web/20230606095948/https://lubimyczytac.pl/ksiazka/4897078/o-polnocy-w-czarnobylu):
```
<nav aria-label="breadcrumb" class=" ">
<ol class="breadcrumb ">
<li class="breadcrumb-item">
<a href="/web/20230606095948/https://lubimyczytac.pl/">lubimyczytać</a>
</li>
<li class="breadcrumb-item">
<a href="/web/20230606095948/https://lubimyczytac.pl/ksiazki">Książki</a>
</li>
<li class="breadcrumb-item">
<a href="/web/20230606095948/https://lubimyczytac.pl/ksiazki/k/46/reportaz">Reportaż</a>
</li>
<li class="breadcrumb-item active" aria-current="page">O północy w Czarnobylu</li>
</ol>
</nav>
```
New path (https://lubimyczytac.pl/ksiazka/4897078/o-polnocy-w-czarnobyl …

Fix tags xpath for lubimyczytac.pl

---

cps/static/css/caliBlur.css

fix for #2838

---

cps/translations/zh_Hans_CN/LC_MESSAGES/messages.po

Fix "OAuth Client Id" translation error.

Fix messages.po in zh_Hans_CN

---

cps/static/js/kthoom.js
cps/templates/readcbr.html
cps/web.py

On each page change save the position as a bookmark.
When loading the comic, use the last known position.

Comics save last position

---

cps/static/css/caliBlur.css
cps/static/js/caliBlur.js

Adding back shelves action on search template

---

cps/translations/nl/LC_MESSAGES/messages.po

I have added nearly all of the Dutch translations that were empty.

Updated Dutch translation.

---

cps/tasks/metadata_backup.py

I added this path to generate identifiers into metadata.opf file.

Generate identifiers in opf metadata file

---

cps/translations/sl/LC_MESSAGES/messages.po

After checking the nightly build I have made some improvements.

Updated Slovenian translation

---

cps/cover.py
cps/helper.py

Transform color space to srgb instead of rgb to prevent dark images

---

cps/kobo.py

Allow POST requests issued during Overdrive book returns to be proxied
