janeczku/calibre-web

cps/db.py
cps/static/css/typeaheadjs.css
cps/static/js/bootstrap3-typeahead.js
cps/templates/edit_book.html
cps/templates/layout.html
cps/web.py

I had a lot of Authors 'Unbekannt' in my library. When i entered a Author in the Web interface all 'Unbekannt' where edited. With this fix a new Author is added to the db and linked to the book.
It would be better to use gettext instead of `if book.authors[0].name not in  ("Unknown", "Unbekannt", "", " "):` but that seemed to complex for me.
Added Typeahead for Author input
thats my first github pull request. i wanted to seperate it in two parts; didn't work.

Fixes for editing Authors and adds Typeahead for Author input

---

cps/static/css/colors.css
cps/static/css/style.css

Google Font urls now default to HTTPS which is good practice, plus it will fix the below error for servers using SSL.

Update Google Font protocol to HTTPS

---

cps/ub.py

Required when running in Docker container where you need to expose the port

Allow overriding default port with environment variable

---

cps/epub.py

Scenario 1.
Read img tag of cover file if cover is (x)html
for example
`<item id="cover" href="Text/cover.xhtml" media-type="application/xhtml+xml”/>`
Scenario 2.
situation when opf file content is
`<meta name="cover" content="cover.jpg"/>.`
then
`<item id="cover.jpg" href="Images/cover.jpg" media-type="image/jpeg"/>`
before patch, only check id="cover" no according to meta instruction

More detecting cover when uploading epub file

---

cps/web.py

File attachment should be url encode rather than pure utf-8 format when unidecode unavailable

Fix attachment filename

---

cps/ub.py

This change allows us to run multiple libraries without needing multiple instances of the engine.
Since app config is all in the db, we get no port conflicts and be able to run multiple instances of this app with no issues.
Using os.getenv instead of os.environ.get allows us to provide CALIBRE_DBPATH inline with the invocation of the file (`CALIBRE_DBPATH=/foo/bar/` python cps.py)

Read dbpath from $CALIBRE_DBPATH if present

---

cps/static/css/style.css

This adds some space between the buttons when viewing them on a mobile device. It affects the buttons on every page that has the `.discover` class wrapping the contents, including the shelf, admin, SMTP, and profile pages.
With the style change, this
becomes this
Please let me know what feedback you have.

Add padding to bottom of buttons

---

cps/redirect.py
cps/templates/admin.html
cps/templates/config_edit.html
cps/templates/login.html
cps/templates/remote_login.html
cps/ub.py
cps/web.py
readme.md

When using a device that is bothersome to log in on (e.g. a Kindle) you can use a magic link to log in via another device.
Configuration was added and is disabled by default.
I recognize this is very firmly in the enhancement category, and you might not be interested. But when I went to log in on my Kindle and looked at my 30 character password I thought "there has got to be a better way". In case I'm not alone in that pain, I figured I'd chance a pull request.

Add "magic link" functionality

---

cps/templates/user_edit.html

Same fix made with 92f634b6a6a2bcabaa4263ba4ec4e353f1b4bc26, different template.

[Fix] Associate label with correct input

---

cps/static/js/edit_books.js

Event and selectors appear to have been accidentally combined. The result is that typing in any input triggers a call to the `/get_matching_tags` route. We can probably limit the selector farther to only fire when `#tags` is typed into.

Split event listener and selector string

---

cps/helper.py

When SMTP is configured to use a service that doesn't use an email address to log in – e.g. AWS SES or Postmark – the sendmail request fails saying the FROM address is invalid.
With this change, I was able to send using both Gmail and AWS SES. Previously, AWS SES failed saying "Invalid MAIL FROM address provided" because the IAM user access key is not an email address.

Send mail from the FROM address instead of the login

---

cps/web.py

Try to retrieve `SECRET_KEY` from an environment variable before falling back to the default key.
I'm not sure if there's anything performing encryption right now (since calibre-web doesn't appear to use Flask's `session` object) but in case that changes in the future, I think the option should exist to use a non-default key (especially since the current one comes straight from Flask's online documentation).

Use SECRET_KEY from environment variable

---

cps/static/css/style.css
cps/static/js/details.js
cps/templates/detail.html
cps/templates/layout.html
cps/web.py

Instead of redirecting the user away from the page or causing a full refresh, the user is able to add books to multiple shelves in quick succession.
If JavaScript is disabled, it gracefully falls back to a standard request (the current behavior).

Use ajax to add/remove books from shelves

---

cps/templates/layout.html
cps/web.py

Default view still shows the latest books, but includes ability to show oldest books, and books sorted alphabetically (ascending & descending).
I did not include translations for the next text, but they are split up for easy translating and are otherwise ready for translating.
Please let me know if there's any configuration that you would like me to include or any feedback you have.

Add sort options when viewing books

---

cps/static/js/main.js
cps/templates/detail.html
cps/templates/discover.html
cps/templates/fragment.html
cps/templates/index.html
cps/templates/layout.html
cps/templates/search.html
cps/templates/shelf.html
cps/web.py

With them shown in a modal, you don't lose your place in the pagination. If the request comes via Ajax, the minimal layout is used. If via a normal request, the full layout is used. That lets you open the details in a new tab and have the full experience, but if you're clicking through the results of a search, you can view many without losing your place.
While I was going through my library, marking everything that I'd read, I was annoyed by the need to open the books in a new tab or risk losing my place in the pagination.
Please let me know what feedback you have. Thanks!

Show book details in modal dialog

---

cps/web.py

Ran into this while testing an unrelated change a couple weeks ago.

Do not attempt to create the YAML file when Google Drive is disabled

---

cps/helper.py

Now, on send test email try got an exception:
```
File "/opt/calibre-web/cps/helper.py", line 179, in send_raw_email
mailserver.login(settings["mail_login"], settings["mail_password"])
File "/usr/lib/python2.7/smtplib.py", line 607, in login
(code, resp) = self.docmd(encode_cram_md5(resp, user, password))
File "/usr/lib/python2.7/smtplib.py", line 571, in encode_cram_md5
response = user + " " + hmac.HMAC(password, challenge).hexdigest()
File "/usr/lib/python2.7/hmac.py", line 75, in __init__
self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode
```

Fix hmac creation in send_test_email function

---

cps/templates/layout.html

I imagine these buttons are still in use when JavaScript is disabled or not loading.
Ref #252

Add "Previous" pagination button

---

cps/epub.py
cps/web.py

Automatically reads the dc:subject tag on epubs to autofill the Tags field when uploading a new book to the library

Added tags metadata handler for epubs

---

cps/static/css/style.css

Improve readability of the labels by separating them 5 px.
Before:
After:

Added separation for input labels in advanced search view

---

cps/templates/config_edit.html
cps/templates/user_edit.html
cps/ub.py
cps/web.py

Uses a configurable list of tags to denote what is mature and hides those books from the user.
All current users will have "Show mature content" checked and will have to manually be changed after updating to this. New users will have it unchecked by default. I figure that it is better to be conservative with new users while maintaining the same functionality current users have been experiencing.
Resolves #262.

Add option to hide mature content from some users

---

cps/web.py

Please add change to allow that book uploaded with upercase extension will work. 
Currently the books can be uploaded but no download or view online possible.

fix books with uppercase extension

---

.editorconfig
.eslintrc
cps/static/js/details.js
cps/static/js/edit_books.js
cps/static/js/get_meta.js
cps/static/js/main.js
cps/static/js/shelforder.js
cps/templates/book_edit.html
cps/templates/detail.html

Attempts to pattern what has been in use by Codacy. Currently, it eliminates support for IE10 and below, and some aspects of our code eliminate IE11, leaving Edge as the only supported MS browser. I don't think this is intentional.
Assuming we want to continue supporting at least IE 11, we should (a) change all of the code to EMC5 standards or (b) use [Babel](https://babeljs.io/) to transpile to EMC5.
Thoughts?
Resolves #242

Add eslint file

---

cps/web.py

That way we can use dynamic URLs, such as those returned by the "Get Metadata" request.
Ref #270

Check if JPEG via response content-type header instead of URL extension

---

cps/cache_buster.py
cps/web.py

Calculates MD5 hash of static assets on server start. These are appended to the file name's when url_for is used, telling browsers to download the latest version of the files, e.g. `style.css?q=81cf0ee`.
Inspired by https://github.com/ChrisTM/Flask-CacheBust but uses query strings instead of rewriting the path because fonts inside CSS files break when the path is rewritten.

Add static asset cache busting

---

.gitignore
readme.md

Directory will automatically get created when it's used as pip's target, and this way we don't have to (a) live with seeing all of the dependencies as untracked changes or (b) add `vendor` to `.git/info/exclude`.
I can't think of any downsides to this.

Remove vendor directory from git

---

cps/static/js/edit_books.js

Some items are still using ES6 syntax, which will break on IE11 and Safari.
I also updated some minor items to conform with our ESLint configuration.

Use ES5 syntax

---

cps/web.py

Re-apply `db_filter`that was accidentally removed when the language and content filters were moved to `common_filters`.
Fixes #302

Fix filter regression

---

cps/templates/user_edit.html

fixes #312 In order to make the option safe and sane we move the corresponding checkbox to the settings that need administrator privileges.

Move "Show mature content" Checkbox

---

cps/templates/layout.html
cps/templates/stats.html

With many browsertabs open the user hardly can see my library's name of choice.
I think it would be nice if the library title can be reflected in the logo text, to feel more like 'home' so to speak. In exchange I added a small "powered by" line in the stats page that links to the github repository.

Customize the Logo Text

---

cps/cache_buster.py

I attempted to run `cps.py` using python3 and got this error:
```
File "cps.py", line 13, in <module>
from cps import web
File "/home/calibre/Git/calibre-web/cps/web.py", line 38, in <module>
import helper
File "/home/calibre/Git/calibre-web/cps/helper.py", line 40, in <module>
import gdriveutils as gd
File "/home/calibre/Git/calibre-web/cps/gdriveutils.py", line 16, in <module>
import web
File "/home/calibre/Git/calibre-web/cps/web.py", line 216, in <module>
cache_buster.init_cache_busting(app)
File "/home/calibre/Git/calibre-web/cps/cache_buster.py", line 28, in init_cache_busting
file_hash = hashlib.md5(f.read()).hexdigest()[:7]
File "/usr/lib/python3.6/codecs.py", line 321, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final) …
```

python3 compatibility

---

cps/db.py
cps/web.py
optional-requirements.txt

SQLite natively supports case-insensitive search only for ASCII data (implementation of lower() and upper() that are used internally by SQLite are not Unicode-enabled). A solution is to redefine a lower() function on a DB connection and replace SQAlchemy like() calls with ilike() calls.

Case-insensitive search for non-ASCII queries (#368)

---

cps/web.py
optional-requirements.txt

I noticed that some of my cbz files were being displayed in a reversed order(page 1 was '020.png', page 2 was '019.png', etc...)
Fix: sort file names in `web.py` before sending back a requested page.
Also, I added a optional requirement for the `natsort` package (supports both python 2 and 3). Since the filenames are strings, the built in `sorted` function may have issues with proper page order.
```
>>> sorted(['1', '2', '10', '5', '12', '21', '18', '4'])
['1', '10', '12', '18', '2', '21', '4', '5']
>>> from natsort import natsorted as sorted
>>> sorted(['1', '2', '10', '5', '12', '21', '18', '4'])
['1', '2', '4', '5', '10', '12', '18', '21'] 
```

file order fixed for some comic books

---

cps/templates/detail.html

When the book's extension is .azw3 and downloaded by kindle's experimental browser, 'anyname' would be used as the name of the book in URL. In this case, the format of book will be in capital, which cannot be opened in Kindle Paperwhite.
Kindle Paperwhite firmware: 5.9.4

fix(template): download book with .AZW3 in kindle's browser

---

readme.md

I had quite a hard time to configure Google Drive integration, and I'm not the only one (cf. https://github.com/janeczku/calibre-web/issues/185), so I added information about :
- client_secrets.json file that seems to be required
- the need to click "Submit" BEFORE clicking "Authenticate Google Drive"
Of course, this is open for discussion !

Add documentation about Google Drive integration in README

---

cps/converter.py

Before the command was not working correctly to check the calibre version since it seemed to be treating the entire string as the command.  So when ' --version' was added it was breaking.  I changed the format to pass the command and args as a list and it seems to work correctly.

Changed the args to subprocess.Popen to pass args to the command

---

cps/db.py

Calibre allows `url:` as a kind of book identifier and shows it in the UI as a link; this change makes calibre-web do the same.

Render 'url:' ID type as a link

---

optional-requirements.txt

changed optional requirement from lxml==3.7.2 to >=3.8.0 ebook-convert is not working properly with a version < 3.8.0
related to this discussion https://github.com/janeczku/calibre-web/issues/627

Update optional-requirements.txt increase requirement lxml to >=3.8.0

---

cps/static/css/style.css
cps/templates/http_error.html
cps/web.py

Hello,
this PR beutifies the http errors.
Instead of the standard "not found" etc. page we get a nicer one.
@OzzieIsaacs should be localize the error messages too?
Right now the english message comes directly from werkzeug.HTTPException

Beautify http errors

---

cps/server.py

I was running calibre on a docker container, and i tried to set up SSL just as an experiment. I later decided to not use SSL on the container and having it on the web server. I removed the certificate and key files from the container, expecting the app would fallback to not use SSL. That didn't happen, it crashed, and since it crashed, i could not easily update the settings from the GUI.
I guess the solution was to enter the database and removed manually from there, but i think a user should not be expected to fix the problem that way. My solution was to simply delete the configuration database, which did work, but was far from ideal.
Falling back to not use SSL if the paths are broken seems a sensible approach to me. Maybe further verification of the files should be done, but i think …

Verify if certfile and keyfile are paths to actual files

---

cps/helper.py
cps/templates/detail.html
cps/web.py
cps/worker.py

Here is my interpretation of a fix for #295.
Added a pre-render check to ensure if we should expose the Send to Kindle button.  The check is based on what converter is configured (if any) and what available formats are currently in the system for that book.
Small bug fix to ensure that any new book added to the calibre database has a format field that is all capital letters.  
If a book now has any of the following formats, the system will send a mobi to the kindle:  ePub, azw, azw3.
I don't have any azw files - but I did test this with a book that only has azw3 version and it works.  The assumption I'm making here is that ebook-convert can convert an azw file to mobi.  I couldn't find if it could in the ebook-convert documentation.

295   send azw to kindle

---

cps/web.py

Babel supports likely subtags (see [here](http://babel.pocoo.org/en/latest/locale.html#likely-subtags)).
We just need to process Accept-Language values using Locale.parse().

A better solution to #681

---

cps/web.py

At the moment, calibre-web will raise an internal 500 error if an invalid locale identifier is passed in through the `Accept-Language` HTTP header (for a non-logged-in user).
This breaks some crappily-built OPDS feed readers, and there's no reason to error out so severely. This commit just gracefully falls back to `en` if it can't parse the locale identifier.
Fixes #743 among others.

Deal gracefully with invalid Accept-Languages header

---

cps/web.py

When I am trying to add an existing language to a book I am getting something similar to #701 
The problem in the case of language is the element exists so 
https://github.com/janeczku/calibre-web/blob/677264950d75ec9cab9e131e800218912d5f1304/cps/web.py#L586
Its false.
Then you are checking for 
https://github.com/janeczku/calibre-web/blob/677264950d75ec9cab9e131e800218912d5f1304/cps/web.py#L597
and in the case of language is also false, so you fall into
https://github.com/janeczku/calibre-web/blob/677264950d75ec9cab9e131e800218912d5f1304/cps/web.py#L601
but the language doesn't have .name attribute and the exception rises.

Fix adding an existing language to a book

---

cps/static/js/caliBlur.js

Previous code was not targeting right element, additionally was only removing a single leading space. New regex will remove any leading spaces from span

Remove leading space in span

---

readme.md

Updated the readme to explain their differences. Namely that technosoft's can convert while lsio's can't.
linuxserver.io's image is much more popular so it's important to point out that people are losing functionality by using it.

Explain difference between Docker images

---

cps/templates/detail.html

The ID of this button is currently `sendbtn` if the condition is true, but `sendbtn2` when false. Propose renaming both to `sendbtn` as neither button will render on screen at the same time. This will assist in caliBlur more easily targeting both states, rather than individually targeting the same button twice

Update ID of button from sendbtn2 to sendbtn

---

cps/web.py

The current import for some local modules causes errors when those already exist in site-packages on the target system.
Namely "import db" is ambiguous and may cause errors due to loading of the 'db' PyPI package instead of the module.

Force namespace resolution of imports

---

cps/static/css/style.css

When the meta-information list is long, it will exceed the screen. I fixed it

[fix] add a scroll bar to a long list of meta information

---

cps/static/css/style.css
cps/static/js/main.js
cps/templates/author.html
cps/templates/config_view_edit.html
cps/templates/discover.html
cps/templates/index.html
cps/templates/search.html
cps/templates/shelf.html
cps/ub.py
cps/web.py

Hi there,
I've added a book to calibre-web which has many authors.
While this works technically perfect, it will "break" the layout.
This PR introduces a function to calibre-web which shortens the display of authors if there are too many.
The default is set to 5 authors.
By clicking on the 3 dots the whole list with authors will expand. Clicking on "reduce" the list will be reduced again.
The behavior can be modified in "UI configuration":
Setting the value to 0 will deactivate the "reducing" which results in the same behavior like calibre-web is acting now.

Shorten the display of authors if there are too many

---

cps/epub.py
cps/isoLanguages.py
cps/web.py

Some Linux distributions do not provide iso-639 as a system package (Debian at least).
This patch uses pycountry as a fallback, is iso639 cannot be imported, making it easier to run calibre-web without the use of pip.

support pycountry if iso-639 is not available

---

cps/reverseproxy.py

Use HTTP_X_FORWARDED_HOST since HTTP_X_FORWARDED_SERVER holds the hostname of the proxy server on HAProxy/Traefik.
This causes problems on redirects for users of these systems. See https://httpd.apache.org/docs/2.4/mod/mod_proxy.html for more details about this.

Use HTTP_X_FORWARDED_HOST instead of HTTP_X_FORWARDED_SERVER

---

cps/web.py

While searching Custom boolean columns in advanced search an "Internal Server Error" is returned if calibre does not have a custom_column_1 in the DB.
The line causing the error appears to be side-effect free, so the bug is fixed by removing it.
Traceback of original Error:
```
[2019-05-05 18:03:03,597] ERROR in app: Exception on /advanced_search [GET]
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File …
```

1-Line Fix for "Internal Server Error" on advanced search

---

.gitignore
cps/comic.py
requirements.txt

Basic metadata (title/author/cover-if-jpg/etc.) is now extracted from comics if it's in a format comictagger supports. CBR's are still disabled, mainly because libunrar is a hassle and a half.

Use comicapi to enable basic metadata reading for CBZ/CBT files

---

MANIFEST.in
setup.cfg
setup.py

Closes https://github.com/janeczku/calibre-web/issues/456.
Given a recent version of setuptools (pip install -U pip setuptools), you can now do:
* `pip install -e .`
* `pip install -e .'[gdrive]'`
* `pip install -e .'[goodreads]'`
Questions:
* Did I get the right dependencies in the extras (from optional requirements.txt)?
* Would you also like to integrate https://github.com/pypa/setuptools_scm/ for versions?
* Needed for https://github.com/janeczku/calibre-web/issues/677 or some workflow.

Add initial setuptools integration

---

readme.md

I've changed the info as our repository is now multiarch rather than separate repositories for each architecture, we've updated the CI pipeline to rebuild on Calibre-Web releases and check your Github API hourly, I rewrote this recently and we added the ability to optionally pull an extra docker manifest layer to install Calibre binaries to enable ebook conversion, rather that just install it be default, which more than doubles the container size.

Update Docker Info

---

cps.py
cps/__init__.py
cps/about.py
cps/admin.py
cps/logger.py
cps/server.py
cps/ub.py
cps/updater.py

On unix platforms, the http server can be bound to a socket file instead of a TCP socket.
This can provide another layer of security; any local user can connect to the TCP socket, but file permissions can restrict access to the socket file.

support binding the http server to a unix socket file

---

cps/templates/shelf.html
cps/templates/shelfdown.html
cps/web.py

This PR adds a new layout page for a shelf: a very basic simple layout with direct buttons for downloads. This is useful to download selected books of shelves to e-book reader devices (like Kobo) where the standard Calibre menu and scrolling pages with pictures is quite broken.
The new page can be reached via button link 'Download' from the specific shelf's page:

Shelf - simple only-downloads view

---

cps/shelf.py
cps/templates/layout.html

Fix for a typo from 4708347c16fcabc4a620cd9489984106c5794890. Should resolve https://github.com/janeczku/calibre-web/issues/1002

Fix for missing public shelves

---

cps/web.py

Hola. 
I've noticed that when the search template is rendered the page's tab title is incomplete. 
Even if the query GET param is empty or has a value, no title parameter was passed in the render function.
My fix was adding the parameter. Take a look and let me know what you think

Hotfix for search title

---

cps/admin.py
cps/config_sql.py
cps/templates/admin.html
cps/templates/config_edit.html
cps/web.py

This PR enables login via the contents of a header set by some upstream proxy.
If you're using this feature, it's assumed that there's no access to the calibre-web service without going through the proxy responsible for setting the headers, as it allows for unchallenged login (i.e., it assumes the login challenge happens upstream, in some SSO flow).
Fixes #1105

Login via header sent from proxy

---

cps/static/js/caliBlur.js

caliBlur theme uses split method to separate custom columns key and value with the colon separator.
However, when the value contains colons, it splits too many times, which ends up to a truncated output.
This quickly fixes this behavior (split, shift, then join) to get the correct output.

caliBlur theme: fix custom column display that contain colons

---

cps/templates/user_edit.html

kobo token generator function 'kobo_auth.generate_auth_token' is related to a user id, which is not
present on new user page.
Disable the Kobo token part when creating a new user.

new user: disable kobo token on new user page

---

cps/kobo.py

I'm still not sure why you had to change the '>' operator to '!=' when you were testing #1100, but hopefully this resolves the issues you were seeing?

Fix bug where last_created is incorectly set in the SyncToken.

---

cps/admin.py

Hello again.
The view logfiles feature works as expected for accesslog file, but for calibre-web.log, /admin/logfile returns always the "Stream output, can't be displayed" message.
Template logviewer.html expects a log_enable parameter `{% if log_enable %}` , but in the render function it's totally missing.
Because the **View logfiles** button is always visible, and i couldn't find any setting that could disable the logfile view, i assumed that this parameter should be True as default.
Hope I'm clear. All the best

Fix for viewing error logfile in admin

---

cps/translations/zh_Hans_CN/LC_MESSAGES/messages.po

The "Read" string here stands for "have read already" instead of "to read".

Update Simplified Chinese translation

---

cps/web.py

When an authenticating reverse proxy (e.g. Keycloak Gatekeeper) adds a Bearer token in the Authorization header, every request fails with HTTP status code 500.  The corresponding error in the logs is: binascii.Error: Incorrect padding. 
Despite "reverse_proxy_header_login" is enabled, calibre-web tries first to base64decode the bearer token and fails. This patch just reverses the order in which the authentication methods  are checked.

fix binascii.Error with reverse proxy bearer token

---

cps/config_sql.py

Fix for the next error after update:
File "cps.py", line 34, in <module>
from cps import create_app
File "/home/rewerson/lib/web/cps/__init__.py", line 68, in <module>
config = config_sql.load_configuration(ub.session)
File "/home/rewerson/lib/web/cps/config_sql.py", line 348, in load_configuration
update({"restricted_tags": conf.config_mature_content_tags}, synchronize_session=False)
File "/home/rewerson/.local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3862, in update
update_op.exec_()
File "/home/rewerson/.local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1693, in exec_
self._do_exec()
File "/home/rewerson/.local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1874, in _do_exec
values = …

restricted_tags -> denied_tags

---

cps/editbooks.py
cps/templates/book_edit.html

Adds a simple way of editing identifiers on a book.
Implementation remark: I tried to modify the `modify_database_object`, but it seems this function is clearly designed to manage fields that are a list of strings (author, tags, series, languages, etc.), and not key/value based fields.
In the end, I created a new function to avoid polluting the original function.
If you have some ideas on how to merge both "generic" modify_database_object and the identifiers one, I would be interested.
Note: this is my first "draft" pull request, I am very unsure of its consequences (I hope it is the same as "WIP" merge request on gitlab)

edit book: manage identifiers

---

cps/kobo.py

- Fix incorrect maintenance of the SyncToken timestamps.
- Fix issue where the SyncToken isn't included in the response when kobo_proxying is disabled.

[Kobo] Fixes to the Kobo SyncToken.

---

cps/kobo.py
cps/services/SyncToken.py
cps/ub.py
cps/web.py

Add support for the Kobo's State syncing API.
This change has the following effect on Kobo users:
- Completing a book (or marking it as Finished) on the Kobo device, will mark it as read on CalibreWeb, and vice-versa. 
- Adding a book or changing its Read bit in CalibreWeb will push it to the front of the "Recent" book list on the Kobo device.
- (**Untested**) Syncing after a device reset should hopefully also restore books' Read status and current reading location.
Note that this PR syncs and stores more data than is displayed in the CalibreWeb UI (time spent reading, time remaining, number of times read, etc). Displaying that data in CalibreWeb could be a cool UI project if anyone is interested.

[Kobo] Support syncing ReadingState to Kobo devices.

---

cps/shelf.py
cps/templates/feed.xml
cps/templates/layout.html

This addresses #645, in summary:
- A user can create a private shelf with any name so long that they don't already have a private shelf that has that same exact name.
- A user can create a public shelf with any name so long as there is not already a public shelf that has that same exact name.
- Tests (ran sequentially after setting up preconditions):
- Preconditions
- 0 shelves of any kind in the system
- User A 
- Try create private shelf X = shelf created
- Try create private shelf X = error
- Try create public shelf X = shelf created
- Try create public shelf X = error
- Remove private shelf X, create private shelf X = shelf created
- User B 
- Try create private shelf X = shelf created
- Try create public shelf X = error
- Same as create=> the new name should obey the same rules
- …

allows same names for public/private shelves

---

cps/kobo.py

- The image_url_template and image_url_quality_template do not resolve correctly for me when wsgi_app.is_proxied is true. I serve the library under https://<ip>/calibre, and the image_url_template would end up as <ip>/calibre/calibre/etc.
- We weren't generating a request to the correct endpoint when redirecting cover requests to the official Kobo store.

[Kobo] Fix issue with covers

---

cps/admin.py
cps/config_sql.py
cps/opds.py
cps/services/simpleldap.py
cps/templates/admin.html
cps/templates/config_edit.html
cps/web.py

Hey there, I've been wanting to use this functionality for awhile as it's the last part of my home server that isn't integrated with LDAP. I attempted enabling and using the existing code and got it to work, but I ran into a couple of problems. I started to fix them as I came across them, and ending up adding additional functionality along the way. I'd like to address the main questions you asked in #956 so that we can get this enabled for more calibre-web users. #263 
The main thing I added was an LDAP User Import which replaces the create user button when selecting LDAP as the login type. It works by querying an LDAP group (everyone in the supplied ldap group is added), so there's a few extra parameters that are needed. It'll pull in username, password, email, (if there's a secondary …

LDAP Import Users + Usability/Bug Fixes

---

cps/editbooks.py
cps/kobo.py
cps/opds.py
cps/services/SyncToken.py
cps/shelf.py
cps/ub.py

Implements the v1/library/tags set of endpoints to sync CalibreWeb
shelves with the Kobo device.
Drive-by: Refactors shelf.py to consolidate how user permissions are checked.
Drive-by: Fix issue with the sync endpoint that arrises when a book is
hard-deleted.
Tested: I've been using this for the past week without noticable issues, although I'll admit I don't use Shelves as much now that Kobo has added the Series tab.

[Kobo] Add Shelf/Collection support.

---

cps/__init__.py

@OzzieIsaacs After spending several hours digging the github oauth problem #1307 , I finally makes it work with https domains.
First, the nginx configuration is needed to properly proxy the real domain and protocol to Flask, following [this example](https://flask.palletsprojects.com/en/1.0.x/deploying/wsgi-standalone/#deploying-proxy-setups).
And pyopenssl model is required: `pip3 install -U pyopenssl`.
Finally, import `ProxyFix` to make flask properly identity https protocols.
Feel free to test here https://calibre.redbux.cn
Some useful links：
https://stackoverflow.com/questions/54278247/flask-dance-and-error-redirect-uri-mismatch
https://flask-dance.readthedocs.io/en/latest/proxies.html
https://github.com/singingwolfboy/flask-dance/issues/188

Fix https github oauth

---

cps/web.py

Hello,
I am trying to use categories as a first proxy to create story arcs, where I mix multiple series in one big story.
To be able to order them, I was currently using the publication date. When I was using it, I was surprised that the books were first ordered by series before the date.
This PR is about ordering first the books by the dates and then using series information if needed.

Changing ordering logic when showing books from a category

---

.gitignore
cps/templates/feed.xml
cps/templates/index.xml
cps/translations/cs/LC_MESSAGES/messages.po
cps/translations/de/LC_MESSAGES/messages.po
cps/translations/es/LC_MESSAGES/messages.po
cps/translations/fi/LC_MESSAGES/messages.po
cps/translations/fr/LC_MESSAGES/messages.po
cps/translations/hu/LC_MESSAGES/messages.po
cps/translations/it/LC_MESSAGES/messages.po
cps/translations/ja/LC_MESSAGES/messages.po
cps/translations/km/LC_MESSAGES/messages.po
cps/translations/nl/LC_MESSAGES/messages.po
cps/translations/pl/LC_MESSAGES/messages.po
cps/translations/ru/LC_MESSAGES/messages.po
cps/translations/sv/LC_MESSAGES/messages.po
cps/translations/uk/LC_MESSAGES/messages.po
cps/translations/zh_Hans_CN/LC_MESSAGES/messages.po
messages.pot

There are several errors in current opds templetes.
* ~~Not using absolute URL~~
* Not specifying `kind` in `type`
* Some titles and contents are identical
This PR fixes all above. Due to string changes, I also regenerated the translation files. If that's not correct, I can remove that commit.

Fix opds format errors

---

cps/__init__.py

This fixes a trivial authentication bypass,
according to https://flask.palletsprojects.com/en/1.1.x/quickstart/#sessions

Don't use an hardcoded session key

---

cps/web.py

First time doing this, so apologies if it's not following procedures or protocol. Publishers query attempts to sort on the publishers.sort column, which is empty in the calibre database. Order by publishers.name allows publishers to be sorted alphabetically on the Publishers page.

Update web.py to sort Publishers by name

---

cps/admin.py
cps/config_sql.py
cps/helper.py
cps/templates/config_edit.html
cps/web.py

**Intro**
Kobo e-readers use a specific epub variant that allows more advanced capabilities like pages left in this chapter, length of different chapters and faster page turns. 
When using Calibre I transfer files to my Kobo e-reader with the KoboTouchExtended plugin installed. This plugin automatically converts epub's to the so called "_kepubs_" that allow me to use the advanced Kobo features. In my kobo they are shown as being of the "kobo epub" type.
**Problem**
I would like to be able to use calibre-web on the experimental browser on the Kobo to directly download the books to my device without having to connect to a computer. I can do that with the current calibre-web but I lose the "kobo epub" functionality.
Calibre's convert utility that is already integrated in calibre-web is not …

Add automatic epub to kepub conversion using kepubify

---

cps/templates/feed.xml

Using the OPDS feeds with the MoonReader Android application yielded the following error:
"Error parsing XML: unbound prefix".
This was due to a missing namespace in the feed.xml template.
See https://github.com/janeczku/calibre-web/issues/1403 for more
information.

Fix XML parsing error when using OPDS feeds

---

cps/templates/config_view_edit.html
cps/templates/user_edit.html
cps/translations/cs/LC_MESSAGES/messages.po
cps/translations/de/LC_MESSAGES/messages.po
cps/translations/es/LC_MESSAGES/messages.po
cps/translations/fi/LC_MESSAGES/messages.po
cps/translations/fr/LC_MESSAGES/messages.po
cps/translations/hu/LC_MESSAGES/messages.po
cps/translations/it/LC_MESSAGES/messages.po
cps/translations/ja/LC_MESSAGES/messages.po
cps/translations/km/LC_MESSAGES/messages.po
cps/translations/nl/LC_MESSAGES/messages.po
cps/translations/pl/LC_MESSAGES/messages.po
cps/translations/ru/LC_MESSAGES/messages.po
cps/translations/sv/LC_MESSAGES/messages.po
cps/translations/tr/LC_MESSAGES/messages.po
cps/translations/uk/LC_MESSAGES/messages.po
cps/translations/zh_Hans_CN/LC_MESSAGES/messages.po
messages.pot

Updated all instances of "Allow Editing Public Shelfs" to "Allow Editing Public Shelves"

Fix typo "Shelfs" to "Shelves"

---

cps/web.py

**Describe the bug/problem**
Looks like a typo TBH: calibre_db.calibre_db.fill_indexpage() should be calibre_db.fill_indexpage()
Changing cps/web.py line 660 fixes the problem accordingly.
entries, __, pagination = calibre_db.fill_indexpage(page, db.Books, True, [func.randomblob(2)])
**To Reproduce**
Fresh install, library is functioning, all else is functioning.
Click on "Discover"
500 Error
**Logfile**
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception …

removed extra reference to calibre_db (calibre_db.calibre_db..) typo?

---

cps/web.py

Hello.
**Problem:**
When trying to access a book, without being logged in, after logging in I'm always redirected to the `url_for("web.index")`.
**Expected behaviour:**
After successfully logging in, I should be redirected to the book page I was trying to access.
**Solution:**
I modified the `next_url` parameter that gets passed in the `render_title_template('login.html',...)` (cps/web.py : 1437) function so that it can have 2 possible values. 
If the GET param `next` exists, it's value will be used. If not present, then the `next_url` will have the default `url_for("web.index")`.
I couldn't find any issue submitted about this problem, sorry if I missed it.
Thanks, let me know what you think

Fix for hidden input 'next' on login form

---

cps/editbooks.py

This is a very simple change. I was going through the code base and I noticed this bug. With the assignment originally being within the try, if the try failed, the exception wouldn't have access to the value

Move assignment of `new_coverpath`

---

cps/ub.py

When using pypy3 and restarting the calibre web server it prints out "Settings database is not writeable. Exiting...".
After commenting out the try catch clause I found that it was due to the database being locked.
This was odd as when I switched to using python3 to launch the server it successfully wrote to the settings database.
I assumed that it had to do with differences between how pypy3 and python3 garbage collect leading to conn.close() being called implicitly on python3 but not on pypy3.
I changed the "conn = engine.connect()" using the examples at https://docs.sqlalchemy.org/en/13/core/connections.html as an example and this seems to have fixed the problem with launching the server with pypy3. I have also tested the changes with python 2.7.16 and python 3.7.3.

Fixing "Settings database is not writeable. Exiting..." when using pypy3

---

cps/admin.py
cps/config_sql.py
cps/kobo.py
cps/templates/admin.html
cps/templates/config_edit.html

This should help with a fix when downloading from a URL that goes through a reverse proxy, especially through Docker.
As there could be port mappings within Docker (`12345:8083`), then a reverse proxy: (`54321 -> 12345`), and even potential router port forwarding (`34125 -> 54321`). This allows the user to make API calls correctly to links like `api_endpoint` for Kobo.

feat(api): include external port option

---

cps/static/css/caliBlur.min.css

This was affecting the Develop branch because it looks like the edit metadata button had a class change (from `btn-warning` to `btn-primary`). I updated it to just select `btn` so that the style gets applied regardless
Before:
After:

caliBlur! style: Fixes issue with edit metadata button not getting styled correctly

---

cps/oauth_bb.py

The scope is no longer available per https://developers.google.com/+/api-shutdown
Fixes #1472 
Fixes #1573

Remove Google+ OAuth scope

---

cps/db.py

Links to https://www.litres.ru, https://portal.issn.org and http://www.isfdb.org/
examples:
https://www.litres.ru/47453330
https://portal.issn.org/resource/ISSN/1937-7843
http://www.isfdb.org/cgi-bin/pl.cgi?389761

add Litres, ISSN and ISFDB tag references

---

cps/__init__.py
cps/db.py
cps/tasks/convert.py

Recently a global session object was introduced (feacbe8ebd35803ebd9ed88cc931564cfc9bcb86) that allowed another thread to get a local session object for it's own use.
I had a need to not just get a new session, but also utilize functions that come with the CalibreDB class. I couldn't just call the global `calibre_db` variable tho because it contained a session that was incompatible with other threads, and I didn't want to rewrite all the methods to have a session object injected as an argument
This PR aims to improve upon that. the database setup is now done on the class itself. Local sessions can be created using `local_ssession = CalibreDB()`. The `__init__()` function will use the previously set up session maker and set `self.session`. Additionally, it will register itself to the …

Remove global Session object, replace with CalibreDB class

---

cps/templates/author.html
cps/templates/index.html
cps/templates/search.html
cps/web.py

Books with audio formats different than mp3 didn't display audio icon next to author name in list of books.

Fix missing audio icon for other audio formats than mp3

---

cps/kobo.py

When loading books from OverDrive, Kobo readers make requests to `/v1/products/books/external/<overdrive ids>`.
This adds a route to forward these requests to the Kobo Store, so that OverDrive still works when using Calibre-Web's Kobo sync server.
I've tested this manually with my Libra H2O connecting to my Calibre-Web server running on Ubuntu 20.04.1. Without this patch, most OverDrive pages would not load and new loans would not be downloaded during a sync, but after adding this everything seems to work as expected.

Forward Overdrive requests to Kobo Store

---

cps/kobo.py

Related to #1693 - using a kobo specific download link.
I just looked at the code and haven't tested it yet, but I can work on that if this is has any likely hood of being merged.

When serving a download URL via KoboSync, use a URL that is specific to Kobo

---

cps/admin.py
cps/config_sql.py
cps/services/simpleldap.py
cps/templates/config_edit.html
cps/web.py

I created [this feature request yesterday](https://github.com/janeczku/calibre-web/issues/1534), and since I had some free time to implement it, there you go :)
The goal of this pull request is to allow admins to use another LDAP filter to import users, and to use a field as nickname that is not necessarily in the member field of the group.
In my case, I had this format in member field : 
`CN=Firstname LastName,OU=...OU=...,DC=...,DC=...`
but I wanted to use sAMAccountName as login in Calibre-Web.
Note 1 : this is the first time EVER I code in Python, so I might have missed some points
Note 2 : I will be unavailable from 25 july to 10 august

feat(ldap): add a field that allows to override LDAP User Object Filter when a user is imported

---

cps/kobo.py
cps/kobo_auth.py

The Kobo e-readers assume that ebook downloaded during sync are in `KEPUB` format, so they interpret as `KEPUB` even if they are `EPUB`.
This misunderstanding generates strange malfunctions (#1439 & #1484) that affect the reading experience.
The PR #1570 prefers the `KEPUB` format over the `EPUB`, but only if this is available, so the user must perform a manual conversion before starting the synchronization in order to have a correct behavior.
You would have a better user experience, and less error prone, with automatic conversion.
In my opinion the best time to perform this conversion is during synchronization.
In fact, in this way, ebooks are converted only when conversion is strictly necessary and it is ensured that all ebooks synchronized with the Kobo are actually in `KEPUB`.
This PR …

Automatic conversion in kepub during Kobo sync

---

cps/db.py

It should fix the following stacktrace:
```
[2021-02-18 14:46:14,771] ERROR {cps:1891} Exception on / [GET]
File "/opt/calibre/vendor/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/opt/calibre/vendor/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/calibre/vendor/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/calibre/vendor/flask/_compat.py", line 39, in reraise
raise value
File "/opt/calibre/vendor/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/calibre/vendor/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File …
```

Declare variables before using them

---

cps/kobo.py

I think this fixes the problem I brought up in #1908 
Non proxied:
```
curl -qs 'http://localhost:3000/kobo/748fcddbd2434fedc765d0394034d1a6/v1/library/sync?Filter=ALL&DownloadUrlFilter=Generic,Android&PrioritizeRecentReads=true' | jq '.[0].NewEntitlement.BookMetadata.DownloadUrls'
[
{
"Format": "KEPUB",
"Platform": "Generic",
"Size": 412767,
"Url": "http://localhost:8083/kobo/748fcddbd2434fedc765d0394034d1a6/download/1/kepub"
}
]
```
Proxied:
```
curl -qs 'https://proxy/kobo/748fcddbd2434fedc765d0394034d1a6/v1/library/sync?Filter=ALL&DownloadUrlFilter=Generic,Android&PrioritizeRecentReads=true' | jq '.[0].NewEntitlement.BookMetadata.DownloadUrls'
[
{
"Format": "KEPUB",
"Platform": "Generic",
"Size": 412767,
"Url": "https://proxy/kobo/748fcddbd2434fedc765d0394034d1a6/download/1/kepub"
}
] …
```

Use the kobo auth'd version for download link when proxied -- Fixes #1908

---

cps/static/css/caliBlur.css
cps/static/js/main.js

Fixed several issues in caliblur theme:
- Book display no longer has borders that go way outside the cover
- Made the toolbar in book details page less ugly in caliblur
- Fixed the fact that book details view was broken in caliblur if book was scrolled to via infinite scroll (see https://github.com/gilbN/theme.park/issues/168 - this was actually a calibre web problem)

Fixed a few graphical issues and the fact that caliblur book details was broken after engaging infinite scroll

---

cps/static/css/kthoom.css
cps/static/js/kthoom.js
cps/templates/readcbr.html

I found a bug that pushing the space key will move to the previous one when a user sets the reading direction from right to left.  
I think I created this bug when I pushed my pull requests #908. I fixed the problem and now it's fine.

Fix an issue that space key doesn't work intentionally

---

requirements.txt
setup.cfg

remove singledispatch from requirements

---

cps/static/css/kthoom.css
cps/static/js/kthoom.js
cps/templates/readcbr.html

- PR centered around some QoL changes for **Scale: Width** comic readers 
- Added an option to disable y-scrollbar on Comic Viewer
- This helps readers who prefer to use Scale: Width and don't need/want the scrollbar
- Added Reset to Top behavior on Comic Viewer
- After every new page, the Comic Reader will scroll the new page all the way to the top. This helps readers using Scale: Width so they don't have to manually scroll to the top every new page
-  **Reset to Top**: Will always scroll to top after every next/previous page or selecting a page from the ToC
- **Remember Position**: Default behavior
_Missing translations_
_Missing Keyboard Shortcuts_

Added options on Comic Viewer to remove y-scrollbar and reset page scroll after changing pages

---

cps/kobo.py
cps/shelf.py
cps/templates/shelf_edit.html
cps/ub.py

* Added a flag to shelves in order to set whether they must be synchronized with Kobo device.
* Only books on kobo shelves are synchronized.
* Shelves modified after last sync with no kobo sync flag are remove from Kobo device.
* Update db on startup: kobo_sync field to shelf table.
* In order to keep old behavior, if no shelves are marked to kobo sync, all books and shelves are synchronized.
Maybe, it solves/helps: #1276

Added option in order to synchronize only selected shelves on Kobo device

---

.gitignore
cps/static/css/caliBlur.css

- Added `.python-version` to git ignore in case (like me) people manage their python with pyenv and they want to have Calibre use an isolated / stable python version
- Fixed a mobile styling issue for Caliblur. In shelves/search/discover we had:
And now have:

add python-version to gitignore and fixed caliblur on mobile

---

cps/templates/login.html

Stops virtual keyboards, such as the ones on mobile devices, to default to uppercase for the first letter of the login user input field.

Prevent virtual keyboard login auto capitalization

---

cps/constants.py
cps/metadata_provider/amazon.py

added support for amazon metadata by using BeautifulSoup. Sadly it is quite a bit slower than just accessing an API (on an RPI4 a search takes about 10 seconds) as parsing the html can take a while. Also some metadata is only provided sometimes or not at all so for performance reasons I left that out completely. It works really well however if you only care about author and description. also of all metadata providers this should give the highest resolution cover.

added support for amazon metadata

---

README.md

Update links for optional pip features and GDrive integration. 
The optional pip features link was broken and I found a better page to link straight to GDrive integration help.

Updates Links in README

---

cps/admin.py

Signed-off-by: Aisha Tammy <aisha@bsd.ac>
---
This allows setting identifier to `mail=%s` as this wasn't being detected earlier.

allow @ in auto username detection

---

cps/admin.py
cps/db.py
cps/static/js/main.js

Fixes #2419, a bug where calibre-web breaks with an error 500 if one has a working DB configuration and then tries to update the DB path to a non-existent one.

Bugfix for Error 500 when giving non-existend database path

---

cps/static/js/kthoom.js

**Issue**
If .cbz archive is created on a Apple device, it may have __MACOSX folder. Files in that folder may have image extension but are actually not images files. Comic reader renders these files as corrupted pages.
For example:
- Original comic page in the archive root folder: DW_GS_001.jpg 
- Corresponding resource file in the __MACOSX folder: ._DW_GS_001.jpg
**Proposed fix**
Comic reader should ignore all files that have "__MACOSX" in the path.

Fix: ignore special files originating from Apple devices

---

cps/kobo.py

The current approach is to simply set "en" as book language. This PR tries to use the actual language specified in the metadata of the book.

kobo sync: using the actual book language

---

cps/tasks/mail.py

Hello. 
I've noticed that when using the Gmail Account with OAuth2 email settings, 
the status of the task never changes from _Started_ when the email is sent successfully, for errors tho it changes correctly.
Same problem is mentioned here #2471.
Fix was pretty minor, I've just added the _handleSuccess() method call after the gmail function.
Lemme know if it's enough, in my tests everything works ok.
Thanks

Fix: issue 2471

---

cps/static/css/caliBlur.css
cps/static/js/caliBlur.js
cps/templates/layout.html
cps/templates/login.html

Resolves #946.
Most of the caliBlur ui is set using js after the html is loaded (really a hassle), so I tried to simplify the structure and logic because I couldn't fix it as it was.
For Login page I've added 2 buttons (register and home) for both possible settings (allow public registration, allow anonymus browsing)
and for the register page and the rest of the site when user is anonymus, the links are grouped in the profile dropdown
To simplify the logic and make it easier to customize/edit, I've added the _blur_ class on body in the html, so lot of css is applied immediately, and other small changes. 
The class also fixed #2284 (for me the refresh happended on chrome too)
I've tested the changes as much as I could do, hopefully everything is ok.
Let me know if anything
Cheers

fixes for 946, 2284 caliblur

---

cps/templates/read.html

I was looking at some old issues, and I found #487
I've added a fader with percentage values, so the user can scale the font size of the book.
Lemme know if anything else is needed here.
Have a good one

Feature: Added font size fader in reader's settings popup

---

cps/static/js/libs/bar-ui.js
cps/templates/listenmp3.html

When listening to an audio file, the position is sent back to the server every 30 seconds.
But the call was missing the csrf_token in the request, thus getting a 400 bad request.
Addind the csrf_token to the page and the requests allows the call to succeed, and we are able to resume audio playing from the last know position.

mp3 player was missing the csrf_token

---

cps/web.py

According to https://csp-evaluator.withgoogle.com/ the CSP built here is NOT valid (and the blob: value is missing at img-src, so the image is not displayed when reading ebook in a browser)
Before this commit, in Chrome response header you can find 
Content-Security-Policy: default-src 'self'  'unsafe-inline' 'unsafe-eval'; font-src 'self' data:; img-src 'self'  data:; object-src: 'none'; blob:;style-src-elem 'self' blob: 'unsafe-inline';
After :
Content-Security-Policy: default-src 'self'  'unsafe-inline' 'unsafe-eval'; font-src 'self' data:; img-src 'self' blob: data:; object-src 'none'  blob:; style-src-elem 'self' blob: 'unsafe-inline';
and image in viewer are displayed

Content Security Policy syntax was invalid

---

cps/epub.py

I have a book where the `dc:identifier` metadata element does not have an attribute to signify what type of identifier this is. This causes an exception to be thrown on upload and makes the metadata fall back to the default template.
However, this seems to be perfectly valid, so maybe it's better to just skip the tag and return the rest of the metadata. This could be smarter and try to employ some heuristic about which type of identifier it could be, but from what I've seen these can be many different things.
Example metadata:
```
<?xml version="1.0" encoding="utf-8"?>
<package version="3.0" unique-identifier="BookId" xmlns="http://www.idpf.org/2007/opf">
<metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf"> …
```

epub: Skip invalid dc:identifier

---

cps/templates/feed.xml

Adds some metadata to the opds feed (multiple authors and publication date). 
Some reader software picks up on this, others doesn't. What is being displayed and how differs greatly from reader to reader. For example, another way to display multiple authors is 
```
{% if entry.Books.authors.__len__() > 0 %}
<author>
<name>{% for author in entry.Books.authors %}{{author.name}}{% if not loop.last %} &amp; {% endif %}{% endfor %}</name>
</author>
{% endif %}
```
While some can work with both others can only use one or the other. 
So while I'd really like to also add multiple identifiers (ISBN, DOI, Amazon, ...) I have not found a way to have any reader software pick up on it. I'm not sure if it is even worth implementing this. Would greatly appreciate input! Fixes #2402.

Multiple authors and publication date in opds feed

---

README.md

this is built against the formatting changes of https://github.com/janeczku/calibre-web/pull/2742
it includes the original changes from https://github.com/janeczku/calibre-web/pull/2751 which were not included in 2742 plus a new change from us (linuxserver.io) deprecating armhf support.
it corrects the docker-mods section which is incorrect, fixes a dead link, and removes armhf from the listed of supported arches.

[LinuxServer.io] Update README.md to correct outdated links/info

---

cps/helper.py
cps/kobo.py

Proxying cover requests to the Kobo store failed because of way generic covers could be generated for missing covers.
An option `use_generic_cover_on_failure` was previously introduced to disable generic cover generation and return a 404 status code instead, if set to `False`. Because of that 404, the redirect to the Kobo store was never reached.
I've removed all the `use_generic_cover_on_failure` handling, performing the redirect or 404 in the `HandleCoverImageRequest` method instead.

Fix proxy cover images to Kobo store

---

cps/templates/http_error.html
cps/templates/layout.html

I changed the link target of the home button so that it now always links to the calibre-web root. Before, if hosted on a server, it would link to the server root. Like if the app was on www.mypage.com/calibre-web it would link to www.mypage.com
Also, I fixed a typo in the github report link of http_error.html.

fix for home button linking to server root instead of application root

---

cps/uploader.py

I had a PDF to upload where its title (`xmp_info.dc_title['x-default']`) was read in as `' '`. This caused the condition `if not meta.title.strip()` to match and #L91then mutated the variable `meta` from a `namedtuple`/`BookMeta` into a `str`. Any further access of that variable that assumed `meta` to be `BookMeta` (such as in #L92) raised an error. This change should fix that.

don't mutate meta into a str, keep it a namedtuple

---

messages.pot

The current English version of this setting help string is a little odd.
This update changes the sentence to clarify the English sentence structure.

Clarify `Enable Uploads` text.

---

cps/templates/index.xml

"< icon >" is a standard of the OPDS spec, and this commit adds the favicon to the feed. Certain OPDS readers, e.g. FBReader on Windows, respect this tag and will show the same icon as the main page.

Add Favicon to OPDS Feed

---

cps/server.py

This is a small patch to support systemd socket-activation on Linux.
This allows on-demand startup of calibre-web on the first socket connection, which allows me to save resouces on a service that is not in continuous use.
Sockets can be either AF_INET or AF_UNIX, and will the auto-detected

Add support for systemd socket-activation

---

cps/kobo.py

Kobo has introduced a vanity URL to their Akamai CDN config - "https://https://cdn.kobo.com". As a result, requests sent to the old raw Akamai endpoint now through 404s. This is a simple PR that updates to the new URL.
This is visible in the config of a newly bought Kobo Sage (mine):
```
image_host=https://cdn.kobo.com/book-images/
image_url_quality_template=https://cdn.kobo.com/book-images/{ImageId}/{Width}/{Height}/{Quality}/{IsGreyscale}/image.jpg
image_url_template=https://cdn.kobo.com/book-images/{ImageId}/{Width}/{Height}/false/image.jpg
```
Example:
OLD:
https://kbimages1-a.akamaihd.net/1abfb307-457b-4597-b2ea-74beb2eb1478/149/223/false/image.jpg (Throws 404)
New:
https://cdn.kobo.com/book-images/1abfb307-457b-4597-b2ea-74beb2eb1478/149/223/false/image.jpg (Renders Properly)
fixes …

Update KOBO_IMAGEHOST_URL to new CDN endpoint

---

cps/metadata_provider/douban.py

the way of getting douban tag is searching special key word in html str.
but original code pass in a wrong str, html.text is '\n'. so, tag list always none.
#2932

fix the the problem that metadata_provider/douban.py can't get tags info

---

README.md

the link the wiki page had an typo (missing '-') https://github.com/janeczku/calibre-web/wiki/How-To:-Install-Calibre-Web-in-Linux-Mint-19-or-20

fix: link to Linux Mind installation in README.md

---

cps/templates/detail.html

The div with class "real_custom_columns" is now only rendered if the custom_column data exists, removing blank space in details view.

Refactor book view template detail.html to optimize custom_column rendering

---

cps/admin.py
cps/config_sql.py
cps/constants.py
cps/helper.py
cps/tasks/convert.py
cps/tasks/mail.py
cps/templates/config_edit.html

This is a draft PR for embedding metadata when sending to devices. It depends on  #2463. At the moment the Calibre CLI is used to create OPF files, these parts of the code should be deleted once Calibre-Web supports OPF files.

Embed metadata when sending to device

---

cps/static/js/caliBlur.js

This is a FIX FOR #3002 .
After some thought, I've decided to remove the script that was manipulating the book's description.
It was made before the first merge of the CaliBlur theme, but I don't think the JS processing of the book's description is needed there because it didn't return what the user expected.

fixes 3002

---

cps/db.py

This should resolve #2956.  I was hoping to have this functionality myself, so I figured I'd make a quick patch for it.  It just adds recognition for the barnesnoble identifier and generates a link to https://www.barnesandnoble.com/w/###### for that identifier.

Add support for barnesnoble identifier

---

cps/services/SyncToken.py

`b64encode` returns a `bytes` object, meaning that `SyncToken.build_sync_token` returns something like `b'eyrestOfToken'`. When we later set it as a header, Flask (or something else internally) calls `str` on whatever was passed. A `str`'d `bytes` object wraps it in quotes in its repr'd form, so we get `"b'eyrestOfToken"` which is not base64-decodable.
This fixes an issue where sync tokens can never be read and endlessly loop, causing every sync to fail.

fix: change bytes-encoded token to unicode string

---

cps/logger.py

This change enables adding debug logging to calibre-web classes that will be output when debug is enabled in settings without enabling debug level for external modules

feat: base is_debug on effective level vs root log level

---

cps/isoLanguages.py

The default is to use American-style date formats in calibre-web. I live in Australia which uses a different date format. I have added a custom translation to my local install but this causes a crash if selected when viewing books as the code attempts to locate the "en_AU" translations of the [Calibre language names](https://github.com/janeczku/calibre-web/blob/fcc95bd8953c0b1c00c7af1dfd2f3bb3b3c9dbd0/cps/iso_language_names.py#L10550).
In this code change, we look for the string representation of the locale i.e. en_AU, pt_BR. If no names are returned we look at just the language portion i.e. en_AU -> en, pt_BR -> pt.

feat: add handling for regional locales

---

optional-requirements.txt

Currently, doing a `pip install -r optional-requirements.txt` on a non-Windows platform results in an error due to pywin32 being a Windows only package.
We do this in Linuxserver docker images and the nightly tag builds are failing as a result:
https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-calibre-web/detail/nightly/888/pipeline/#step-159-log-1130

Attempt pywin32 install only on Windows

---

cps/editbooks.py
cps/file_helper.py
cps/uploader.py
requirements.txt

Potential solution for https://github.com/janeczku/calibre-web/issues/3044
This PR adds in mimetype checking to ensure that files being uploaded are not maliciously disguised.
Create a bash script:
```
#!/bin/bash
echo "Hello World!"
```
Rename the bash script: (Ensure that server allows `epub`)
```
mv test.sh test.epub
```
Upload the file to confirm that it is not possible as the mimetype is read differently.

Add python-magic for validating mimetypes

---

cps/static/css/main.css

In the Safari browser, it was impossible for me to press the bookmarks button. After removing the `visibility: hidden`; property from `#panels a`, it started working again. 
Setting `visibility: hidden`; on the `#panels a` element makes the entire link (and all its content, including the` ::before` pseudo-element) invisible and not clickable.
I didn't have this problem on Chrome or firefox, and the modification didn't break anything for me.
reference to  issue number #2839

fix bookmarks button for safari browser

---

cps/config_sql.py

Adds the binary paths for FreeBSD:
Calibre Binary Path = ["/usr/local/bin/"]
Unrar Binary = ["/usr/local/bin/unrar"]
Kepubify Binary = ["/usr/local/bin/kepubify"]

Add Binary Paths for FreeBSD in Auto Config

---

cps/templates/layout.html

This change allow share details on whatsapp and another app if 'Enable Anonymous Browsing' is enabled based on https://ogp.me/:
Before:
After:

Add share details metadata

---

cps/db.py

Increase from the default `2000 pages` or 8MB of RAM to 10k pages or up to 40MB of memory, in a library with 15k books this reduce the initial load page from ~500ms to ~400ms, no further increase improved performance if the valu is bigger for a metadata.db of 28MB. Maybe in future consider convert this to ENV VAR or a feature flag to allow create one page by item in metadata.db.
ref.: https://www.sqlite.org/pragma.html
PS:
I tested changes on page size and another pragma with no better result, looks like if the total pages is bigger than the total size of metadata.db he will reside entirely on memory (40MB > 28MB). For libraries with size reduced the memory consumption don't change, only in the case the metadata.db is bigger than 8MB. Another way is change to use `kibibytes` when change …

Increase sqlite calibre metadata.db cache

---

cps/templates/config_edit.html

While configuring a Calibre web instance, I realized that in "Basic configuration", clicking on the label of "Enforce characters (needed For Chinese/Japanese/Korean Characters)" toggles "Enforce lowercase characters" instead.
It seems to be due to a wrong target in "<label for ...>".

Correct a typo on config_password_character

---

cps/helper.py
cps/templates/detail.html
cps/templates/feed.xml
cps/templates/read.html
cps/web.py

This allows the OPDS consumers to distinguish `epub` and `kepub` files as they have the same MIME-type.

Add a title to OPDS links

---

cps/static/css/caliBlur.css

On mobile, when book conversion is enabled and using the cabliBlur theme, the upload menu appears behind the description text area making it difficult (though not impossible with some careful guesswork around where the buttons should be).
This commit fixes the styling of this section so that it no longer appears behind the description text area.

Fix UI bug when book conversion enabled on mobile

---

cps/kobo.py

Fixes #2849 
When notebook sync is enabled, Sync always fails with "synchronization error."
This PR implements POST method for the kobo endpoint.

Fix sync fails with error when "Synchronize Notebooks" enabled

---

cps/__init__.py

Javascript files are served over HTTP with an incorrect Content-Type header because the 'charset' option is duplicated:
$ curl -I http://127.0.0.1:8083/static/js/table.js
HTTP/1.1 200 OK
Content-Disposition: inline; filename=table.js
Content-Type: text/javascript; charset=UTF-8; charset=utf-8
Content-Length: 35967
Last-Modified: Sat, 16 Nov 2024 06:21:28 GMT
Cache-Control: no-cache
ETag: "1731738088.0-35967-471731799"
Date: Sat, 08 Feb 2025 16:30:42 GMT
Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval'; font-src 'self' data:; img-src 'self' data:; object-src 'none';
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000
This header is not RFC 1521 compliant and it's breaking some …

Remove duplicated 'charset' in Content-Type header for Javascript files

---

cps/static/css/main.css

When opening an EPUB file on mobile devices, the settings modal did not display correctly. The modal was either not responsive, misaligned, or partially hidden, affecting the user experience.
How to reproduce:
1. Use a smartphone or smartphone view from the dev tools of your browser
2. Open an epub! 
3. Press settings on the top right corner.
Screenshot before the fix:  
<div align="center">
</div>
Screenshot after the fix:  
<div align="center">
</div>

Fix: Settings Modal Not Displaying Correctly on Mobile EPUB View

---

cps/admin.py

Resolves a 403 response when accessing `/ajax/updateThumbnails` from a session authenticated by reverse proxy.
For some reason, the decorators are swapped on this route specifically, but not the others. This brings the ordering to be consistent with other routes. The login check should happen before the auth check now.

fix: fixes 403 when using proxy auth

---

cps/static/css/caliBlur_override.css

this hides the navbar in mobile resolution before it is moved to the collapsed sidebar to prevent this effect:

hide desktop navbar when in mobile resolution

---

cps/templates/image.html

Title. This PR makes calibre-web feel a thousand times snappier.
In the future, we should probably look into serving the covers at another size and maybe even in different, optimized formats (webp, AV1).

Lazy-load book covers

---

cps/translations/nl/LC_MESSAGES/messages.po

This pull request updates several Dutch translations in the messages.po file to provide more accurate and complete system messages. Some previously missing or incomplete translations have been supplied, and existing entries have been improved for clarity and correctness.
Added missing Dutch translations for system and error messages
Enhanced consistency and usability for Dutch-speaking users
No changes to application logic, only translation updates
These changes help to improve the overall user experience for Dutch users of Calibre-Web.

Improved Dutch translations in messages.po

---

cps/helper.py

Changing the read status in the booklist would fail for archived books with an error the the custom_column doesn't exist.
Unarchived books didn't have this issue.
The issue was that call to retrieve the book by default does not include archived books.
Setting the second parameter in the function call to True ensures that archived books are included.

Fix: Setting read status for archived books in the books list page
